spring:
  batch:
    job:
      enabled: false

tldrtimes:
  ingestor:
    guardian:
      base-url: ${GUARDIAN_BASE_URL:https://content.guardianapis.com}
      api-key: ${GUARDIAN_API_KEY:}
      page-size: ${GUARDIAN_PAGE_SIZE:20}
    ingestion:
      enabled: ${INGESTION_ENABLED:false}
      fixed-delay: ${INGESTION_FIXED_DELAY:15m}
