import { jetbrainsMono, notoSerifKR, playfairDisplay, pretendard, sourceSerif4 } from "@/app/fonts";
import { GlobalProvider } from "@/app/providers";
import "@/app/styles";
import { routing } from "@/shared/i18n";
import { cn } from "@/shared/lib";
import type { Metadata } from "next";
import { hasLocale } from "next-intl";
import { setRequestLocale } from "next-intl/server";
import { notFound } from "next/navigation";
import { type PropsWithChildren } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

type RootLayoutProps = PropsWithChildren<{
  params: Promise<{ locale: string }>;
}>;

export default async function RootLayout({ params, children }: RootLayoutProps) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  setRequestLocale(locale);

  return (
    <html
      className={cn(
        pretendard.variable,
        playfairDisplay.variable,
        sourceSerif4.variable,
        jetbrainsMono.variable,
        notoSerifKR.variable,
      )}
      lang={locale}
    >
      <body>
        <GlobalProvider>{children}</GlobalProvider>
      </body>
    </html>
  );
}
